### ISSUE TITLE
Ошибка кодировки

### ISSUE THREAD

**Issue by fucksh1tty** [Soto4ka37/Yandex-Music-RPC#3]
[19.03 - 18:23] Установлена версия: v1.3.1. Последняя версия на GitHub: v1.3.1
[19.03 - 18:23] Успешная авторизация! Подписка на плюс АКТИВНА.
[19.03 - 18:23] Пользователь активировал программу
[19.03 - 18:23] Произошла ошибка при подключении
[19.03 - 18:23] Аварийное завершение: 'charmap' codec can't encode character '\xe9' in position 49: character maps to 
[19.03 - 18:23] Traceback (most recent call last):
  File "gui\main_window.py", line 140, in connect
  File "modules\discord.py", line 150, in update
  File "modules\debugger.py", line 35, in addSuccess
  File "encodings\cp1251.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\xe9' in position 49: character maps to

**Comment by fucksh1tty** [comment]
при запуске именно твоего плейлиста - выбивает эту ошибку в разных позициях. я в программировании не алё, поэтому прошу прощения, если это моя ошибка

**Comment by Soto4ka37** [comment]
В данном случае ошибка произошла из-за неправильной кодировки символа "é" в названии трека или имени автора.
Исправлю в ближайшее время.

**Comment by Soto4ka37** [comment]
Исправлено в [v1.3.2](https://github.com/Soto4ka37/Yandex-Music-RPC/releases/tag/v1.3.2)
